export const site = {
  name: "Ana Sofia de Miranda",
  handle: "as-miranda",
  email: "miranda.00042@gmail.com",
  location: "Belo Horizonte, MG, Brasil",
  github: "https://github.com/as-miranda",
  linkedin: "https://www.linkedin.com/in/as-miranda",
};

export const projects = [
  {
    slug: "vuei",
    name: "VUEI",
    kicker: "01 / WEB · EDUCAÇÃO",
    category: "web",
    period: "2026",
    status: "Em desenvolvimento",
    featured: true,
    short: "Vitrine de Serviços das Empresas Juniores do CEFET-MG.",
    description: "Uma experiência digital para organizar e apresentar empresas juniores, serviços e informações de forma clara, navegável e escalável.",
    role: "Responsável pelo desenvolvimento e organização da experiência web.",
    stack: ["Django", "Python", "HTML", "CSS", "JavaScript"],
    problem: "[ADICIONAR INFORMAÇÃO]",
    solution: "[ADICIONAR INFORMAÇÃO]",
    process: "[ADICIONAR PROCESSO]",
    results: "[ADICIONAR RESULTADOS]",
    learning: "[ADICIONAR APRENDIZADOS]",
    links: { github: "[ADICIONAR LINK]" },
  },
  {
    slug: "mocs",
    name: "MOCS",
    kicker: "02 / EDUCAÇÃO · DIPLOMACIA",
    category: "education",
    period: "2026",
    status: "Em atividade",
    featured: true,
    short: "Modelo de Comitês Simulados do CEFET-MG.",
    description: "Projeto educacional que aproxima estudantes de diplomacia, cidadania, debate e relações internacionais por meio de simulações.",
    role: "Participação em organização, produção e desenvolvimento do projeto.",
    stack: ["Organização", "Comunicação", "Web", "Pesquisa"],
    problem: "[ADICIONAR INFORMAÇÃO]",
    solution: "[ADICIONAR INFORMAÇÃO]",
    process: "[ADICIONAR PROCESSO]",
    results: "[ADICIONAR RESULTADOS]",
    learning: "[ADICIONAR APRENDIZADOS]",
    links: { github: "[ADICIONAR LINK]" },
  },
  {
    slug: "flytec-drones",
    name: "Flytec Drones",
    kicker: "03 / ROBÓTICA · SOFTWARE",
    category: "drones",
    period: "2025–2026",
    status: "Projeto / competição",
    featured: true,
    short: "Software, automação, operação e coordenação em um projeto de drones autônomos.",
    description: "Experiência multidisciplinar envolvendo software, automação, planejamento de competição, operação e coordenação de equipe.",
    role: "Atuação em software e coordenação, incluindo automações em Python e atividades de capitã.",
    stack: ["Python", "Mission Planner", "Automação", "Sistemas embarcados"],
    problem: "[ADICIONAR INFORMAÇÃO]",
    solution: "[ADICIONAR INFORMAÇÃO]",
    process: "[ADICIONAR PROCESSO]",
    results: "[ADICIONAR RESULTADOS]",
    learning: "[ADICIONAR APRENDIZADOS]",
    links: { github: "[ADICIONAR LINK]" },
  },
  {
    slug: "expresso-dev",
    name: "Expresso Dev",
    kicker: "04 / SOFTWARE · COMUNIDADE",
    category: "software",
    period: "[ADICIONAR PERÍODO]",
    status: "[ADICIONAR STATUS]",
    featured: false,
    short: "[ADICIONAR DESCRIÇÃO CURTA]",
    description: "[ADICIONAR DESCRIÇÃO]",
    role: "[ADICIONAR MEU PAPEL]",
    stack: ["[ADICIONAR TECNOLOGIA]"],
    problem: "[ADICIONAR INFORMAÇÃO]",
    solution: "[ADICIONAR INFORMAÇÃO]",
    process: "[ADICIONAR PROCESSO]",
    results: "[ADICIONAR RESULTADOS]",
    learning: "[ADICIONAR APRENDIZADOS]",
    links: { github: "[ADICIONAR LINK]" },
  },
  {
    slug: "ghost-band",
    name: "Ghost Band",
    kicker: "05 / CRIATIVO · WORLD BUILDING",
    category: "creative",
    period: "[ADICIONAR PERÍODO]",
    status: "[ADICIONAR STATUS]",
    featured: false,
    short: "Arquivo ficcional e projeto de construção de universo.",
    description: "[ADICIONAR DESCRIÇÃO]",
    role: "[ADICIONAR MEU PAPEL]",
    stack: ["Escrita", "Worldbuilding", "[ADICIONAR]"],
    problem: "[ADICIONAR INFORMAÇÃO]",
    solution: "[ADICIONAR INFORMAÇÃO]",
    process: "[ADICIONAR PROCESSO]",
    results: "[ADICIONAR RESULTADOS]",
    learning: "[ADICIONAR APRENDIZADOS]",
    links: { github: "[ADICIONAR LINK]" },
  },
  {
    slug: "tolkien-arquivo",
    name: "Tolkien / Senhor dos Anéis",
    kicker: "06 / PESQUISA · ARQUIVO",
    category: "research",
    period: "[ADICIONAR PERÍODO]",
    status: "[ADICIONAR STATUS]",
    featured: false,
    short: "Projeto de pesquisa, organização ou produção relacionado ao universo de Tolkien.",
    description: "[ADICIONAR DESCRIÇÃO]",
    role: "[ADICIONAR MEU PAPEL]",
    stack: ["Pesquisa", "Escrita", "[ADICIONAR]"],
    problem: "[ADICIONAR INFORMAÇÃO]",
    solution: "[ADICIONAR INFORMAÇÃO]",
    process: "[ADICIONAR PROCESSO]",
    results: "[ADICIONAR RESULTADOS]",
    learning: "[ADICIONAR APRENDIZADOS]",
    links: { github: "[ADICIONAR LINK]" },
  },
  {
    slug: "escrita-jornalismo",
    name: "Escrita & Jornalismo",
    kicker: "07 / WRITING · REPORTAGEM",
    category: "writing",
    period: "[ADICIONAR PERÍODO]",
    status: "Arquivo",
    featured: false,
    short: "Textos, reportagens e produções autorais reunidos em um arquivo público.",
    description: "[ADICIONAR DESCRIÇÃO]",
    role: "Autoria e produção.",
    stack: ["Pesquisa", "Escrita", "Edição"],
    problem: "[ADICIONAR INFORMAÇÃO]",
    solution: "[ADICIONAR INFORMAÇÃO]",
    process: "[ADICIONAR PROCESSO]",
    results: "[ADICIONAR RESULTADOS]",
    learning: "[ADICIONAR APRENDIZADOS]",
    links: { github: "[ADICIONAR LINK]" },
  },
];

export const posts = [
  { slug: "bem-vindo-ao-arquivo", title: "Bem-vindo ao arquivo", subtitle: "Este site não é uma vitrine estática.", date: "[ADICIONAR DATA]", category: "NOTES", read: "[ADICIONAR] min", excerpt: "Uma nota sobre o que este espaço pretende guardar, organizar e revelar.", tags: ["meta", "arquivo"] },
  { slug: "sistemas-que-nascem-do-caos", title: "[ADICIONAR TÍTULO]", subtitle: "[ADICIONAR SUBTÍTULO]", date: "[ADICIONAR DATA]", category: "TECH", read: "[ADICIONAR] min", excerpt: "[ADICIONAR EXCERTO]", tags: ["[ADICIONAR TAG]"] },
  { slug: "fragmento-001", title: "Fragmento 001", subtitle: "Uma peça curta ainda sem gaveta.", date: "[ADICIONAR DATA]", category: "CREATIVE", read: "[ADICIONAR] min", excerpt: "[ADICIONAR TEXTO/EXCERTO]", tags: ["fragmento"] },
];

export const skills = {
  software: ["Python", "Django", "JavaScript", "React", "HTML", "CSS", "[ADICIONAR]"],
  tools: ["Git", "GitHub", "Mission Planner", "[ADICIONAR]"],
  languages: ["Português — nativo", "Inglês — C1", "Espanhol — iniciante", "Russo — iniciante"],
};

export const experience = [
  {
    period: "2025–2026",
    institution: "Flytec Drones · CEFET-MG",
    role: "Software / Capitã Geral",
    description: "Atuação em software, automação, planejamento e coordenação dentro de um projeto multidisciplinar de drones.",
    technologies: ["Python", "Mission Planner", "Automação"],
  },
  {
    period: "[ADICIONAR PERÍODO]",
    institution: "[ADICIONAR INSTITUIÇÃO / EMPRESA]",
    role: "[ADICIONAR FUNÇÃO]",
    description: "[ADICIONAR DESCRIÇÃO]",
    technologies: ["[ADICIONAR]"],
  },
];

export const education = [
  {
    period: "2024–2026",
    institution: "CEFET-MG · Belo Horizonte",
    role: "Curso Técnico Integrado em Informática",
    description: "[ADICIONAR DETALHES]",
  },
];

export const sections = [
  ["01", "CODE", "/projects"],
  ["02", "PROJECTS", "/projects"],
  ["03", "WRITING", "/archive"],
  ["04", "CURRICULUM", "/curriculum"],
  ["05", "ABOUT", "/about"],
  ["06", "CONTACT", "/contact"],
];
